### ISSUE TITLE
Could not install the app on the device

### ISSUE THREAD

**Issue by thomaslwq** [CntChen/edudemo#1]
@CntChen ，运行react-native run-android的时候出现下面错误。我自己机器的android 环境都是ok的。
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by CntChen** [comment]
error: `JS server already running`
是不是终端命令`react-native start`的执行目录不是当前工程目录

**Comment by thomaslwq** [comment]
我执行的是下面的命令，但是在 android 模拟机下中安装运行不了。
thomaslwq:edudemo dev$ react-native run-android
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by CntChen** [comment]
我在**Ubuntu**上搭建环境后也遇到这个问题，新建的工程可以在模拟器中运行，clone下来的工程不行。
分析：
`react-native run-android`第一步是执行以下命令：

```
// 进入目录
cd android
// 构建工程
./gradlew installDebug
```

单独执行时可以发现`./gradlew installDebug`报错：

> -bash: ./gradlew: Permission denied

因为 ./gradlew是当作可执行程序来调用的，而clone下来的文件**没有执行权限**

解决方法：
让文件获得执行权限

> chmod +x gradlew

参考链接：http://stackoverflow.com/questions/17668265/gradlew-permission-denied

**Comment by thomaslwq** [comment]
好了，可以运行了。Good!
